/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.john.core;

import org.apache.avro.specific.SpecificData;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class MDEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1854910661182134340L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"MDEvent\",\"namespace\":\"com.john.core\",\"fields\":[{\"name\":\"msgId\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"volume\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.String msgId;
  @Deprecated public java.lang.String volume;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public MDEvent() {}

  /**
   * All-args constructor.
   * @param msgId The new value for msgId
   * @param volume The new value for volume
   */
  public MDEvent(java.lang.String msgId, java.lang.String volume) {
    this.msgId = msgId;
    this.volume = volume;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return msgId;
    case 1: return volume;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: msgId = (java.lang.String)value$; break;
    case 1: volume = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'msgId' field.
   * @return The value of the 'msgId' field.
   */
  public java.lang.String getMsgId() {
    return msgId;
  }

  /**
   * Sets the value of the 'msgId' field.
   * @param value the value to set.
   */
  public void setMsgId(java.lang.String value) {
    this.msgId = value;
  }

  /**
   * Gets the value of the 'volume' field.
   * @return The value of the 'volume' field.
   */
  public java.lang.String getVolume() {
    return volume;
  }

  /**
   * Sets the value of the 'volume' field.
   * @param value the value to set.
   */
  public void setVolume(java.lang.String value) {
    this.volume = value;
  }

  /**
   * Creates a new MDEvent RecordBuilder.
   * @return A new MDEvent RecordBuilder
   */
  public static com.john.core.MDEvent.Builder newBuilder() {
    return new com.john.core.MDEvent.Builder();
  }

  /**
   * Creates a new MDEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new MDEvent RecordBuilder
   */
  public static com.john.core.MDEvent.Builder newBuilder(com.john.core.MDEvent.Builder other) {
    return new com.john.core.MDEvent.Builder(other);
  }

  /**
   * Creates a new MDEvent RecordBuilder by copying an existing MDEvent instance.
   * @param other The existing instance to copy.
   * @return A new MDEvent RecordBuilder
   */
  public static com.john.core.MDEvent.Builder newBuilder(com.john.core.MDEvent other) {
    return new com.john.core.MDEvent.Builder(other);
  }

  /**
   * RecordBuilder for MDEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<MDEvent>
    implements org.apache.avro.data.RecordBuilder<MDEvent> {

    private java.lang.String msgId;
    private java.lang.String volume;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.john.core.MDEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.msgId)) {
        this.msgId = data().deepCopy(fields()[0].schema(), other.msgId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.volume)) {
        this.volume = data().deepCopy(fields()[1].schema(), other.volume);
        fieldSetFlags()[1] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing MDEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.john.core.MDEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.msgId)) {
        this.msgId = data().deepCopy(fields()[0].schema(), other.msgId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.volume)) {
        this.volume = data().deepCopy(fields()[1].schema(), other.volume);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'msgId' field.
      * @return The value.
      */
    public java.lang.String getMsgId() {
      return msgId;
    }

    /**
      * Sets the value of the 'msgId' field.
      * @param value The value of 'msgId'.
      * @return This builder.
      */
    public com.john.core.MDEvent.Builder setMsgId(java.lang.String value) {
      validate(fields()[0], value);
      this.msgId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'msgId' field has been set.
      * @return True if the 'msgId' field has been set, false otherwise.
      */
    public boolean hasMsgId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'msgId' field.
      * @return This builder.
      */
    public com.john.core.MDEvent.Builder clearMsgId() {
      msgId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'volume' field.
      * @return The value.
      */
    public java.lang.String getVolume() {
      return volume;
    }

    /**
      * Sets the value of the 'volume' field.
      * @param value The value of 'volume'.
      * @return This builder.
      */
    public com.john.core.MDEvent.Builder setVolume(java.lang.String value) {
      validate(fields()[1], value);
      this.volume = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'volume' field has been set.
      * @return True if the 'volume' field has been set, false otherwise.
      */
    public boolean hasVolume() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'volume' field.
      * @return This builder.
      */
    public com.john.core.MDEvent.Builder clearVolume() {
      volume = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public MDEvent build() {
      try {
        MDEvent record = new MDEvent();
        record.msgId = fieldSetFlags()[0] ? this.msgId : (java.lang.String) defaultValue(fields()[0]);
        record.volume = fieldSetFlags()[1] ? this.volume : (java.lang.String) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
